### ISSUE TITLE
Ambiguous license

### ISSUE THREAD

**Issue by oo13** [Adde-Endless-Sky/AES-Misc#1]
You added GPLv3 as license.txt but no files referred to it, and "copyright" file said that all files were published by CC-BY-SA-4.0.

I suggest updating "copyright" file and adding the license notice to each file in order to ensure your intention.

**Comment by Darcman99** [comment]
The copyright and licensing mimics that of the game the content was created for.

**Comment by MCOfficer** [comment]
it is weird, but still makes sense by my understanding, since CC-BY-SA is GPL3-compatible, i.e. you can publish a heap of CC-BY-SA as a GPL3-licensed project.

**Comment by oo13** [comment]
I just wonder which license you would publish the files by. If you would like to release all files in AES by CC-BY-SA-4.0, you need no changes, although it confuses me.

"copyright" file said that all files were published by CC-BY-SA-4.0, but I guessed that you would like to release some of them by GPL (any version) because you added the license file GPLv3. (If you preferred a certain version of GPL, you must claim it, but you didn't.)

**Comment by oo13** [comment]
I feel your intention became clear.
